### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by kroazi** [TheBlackEntity/ServerSystem#11]
为何我的/tp 100 10 100 服务器回提示我无效参数 以及设置/time  set day or /time set 1000都提示无效参数？

**Comment by TheBlackEntity** [comment]
使用/tppos 100 10 100来传送到坐标。

/time 的工作方式与标准命令一样，但没有 set。
(/time day) 



翻译：DeepL

**Comment by kroazi** [comment]
okay thankyou 我准备翻译cmddoc，因为没有中文版，这让我很难受QAQ，不知道官方何时能出中文版？

**Comment by TheBlackEntity** [comment]
正式版本会有一个网站出来。

不幸的是，这仍然需要时间。我还不确定我想如何设置整个事情。


翻译：DeepL

**Comment by kroazi** [comment]
/back                               server.back.death       在 tp/spawn/warp/home 之前将您传送到您的位置返回死亡地点
                                    server.back.teleport

/baltop                             server.baltop           按余额列出 Top10 玩家（仅在激活经济系统的情况下）

/ban      <玩家>                    server.ban.use          禁⽌玩家进⼊服务器 禁⽌玩家（永久） 禁⽌玩家（暂时）相关 命令：/解禁
          <玩家>                    server.ban.permanent
          <时间|永久>               server.ban.temporary
          <年份<|mo|w|d|h|m|s>
          <理由>

/bc       <消息>                    server.broadcast        向所有玩家⼴播消息

/burn     <玩家><秒>                server.burn             让玩家着⽕

/cgm      <玩家>                    server.checkgamemode    检查玩家的游戏模式

/cc                                 server.clearchat        清除所有玩家的聊天记录

/cec      <玩家>                    server.clearenderchest.self 清除玩家的末影箱
                                    server.clearenderchest.others

/clear    <玩家>                    server.clearinventory.self  清除玩家的物品栏
                                    server.clearinventory.others

/cmdspy                             server.commandspy           向您显⽰其他玩家的聊天/命令条⽬

/createkit  <套件名称>              server.createkit             保存玩家库存相关命令的⼯具包：/删除⼯具包

/day        <世界>                  server.time                  设置世界为白天

/delkit     <套件名称>              server.deletekit              移除工具包

/delhome    <家-名称>               server.delhome                移除⼀个家

/delwarp    <经线名称>              server.delwarp                移除主城

/disenchant                        server.disenchant              移除附魔效果

/disposal                          server.disposal                带gui的垃圾桶

/eco        <设置> <玩家> <金额>    server.economy.use              管理玩家经济设置账⼾余额
            <给予> <玩家> <金额>    server.economy.give           给予玩家金额
            <删除> <玩家> <金额>    server.economy.revoke         删除玩家金额

/schild     <玩家>                 server.extinguish              编辑木牌内容

/enderchest <玩家>                 server.enderchest.self         打开玩家的末影箱
                                    server.enderchest.others
                                  server.enderchest.exempt  

/extinguish <玩家>                 server.extinguish              熄灭玩家的火焰

/feed       <玩家>                  server.feed.self               恢复饥饿值
                                  server.feed.others

/fly        <玩家>                  server.fly.self               允许玩家⻜⾏
                                    server.fly.others

/gm         <玩家><0|1|2|3>                                       设置玩家的游戏模式

/gms       <玩家>                  server.gamemode.survival.self  将玩家的游戏模式设置为⽣存 
                                  server.gamemode.survival.others

/gmc       <玩家>                  server.gamemode.creative.self  将玩家的游戏模式设置为创造模式
                                   server.gamemode.creative.others

/gmsp     <玩家>                   server.gamemode.spectator.self 将玩家的游戏模式设置为旁观者
                                  server.gamemode.spectator.others

/gma      <玩家>                   server.gamemode.adventure.self 将玩家的游戏模式设置为冒险
                                   server .gamemode.adventure.others   

/god      <玩家>                    server.god.self                玩家不再受到伤害
                                    server.god.others

/hat                                server.hat                     将物品放在你当前持有的头上    

/heal     <玩家>                    server.heal.self              治愈玩家并满⾜饥饿感   
                                    server.heal.others

/home      <家>                     server.home.general           将你传送到⼀个家 列出你
                                    server.home.bypassdelay       所有的家

/invsee    <玩家>                   server.invsee.use             查看和编辑其他玩家的背包
                                    server.invsee.exempt  

/ip         <玩家>                  server.ip                     显⽰玩家的IP地址

/kick       <玩家> <原因>            server.kick.use               有理由踢指定球员 
                                    server.kick.exempt

/kickall                            server.kickall                  从服务器踢出所有玩家（除了你）

/kit        <套件名称><玩家>         server.kit.<KIT>.self          给球员⼀个明确的球员套件
                                    server.kit.<KIT>.others
                                    server.kit.bypass.delay

/lag                                server.lag                    向您显⽰有关您的服务器的⼀些性能数据

/wartungen   <on/off>               server.maintenance.toggle     将服务器切换到维护模式 也允许在维护模式下登录
                                    server.maintenance.join      

/money        <玩家>                server.money.self               显⽰玩家相关命令的账⼾余额：
                                    server.money.others

/msg         <玩家><信息>           server.msg                     向玩家发送私信

/mute         <玩家>                server.mute.use                使玩家静⾳  
              <时间|永久>           server.mute.temporary  
              <年份<|mo|w|d|h|m|s>  server.mute.permanent
              <理由>                server.mute exempt
                                    server.mute.temporary.shadow
                                    server.mute.permanent.shadow    

/night       <世界>                 server.time                    将时间设置为晚上

/noon        <世界>                  server.time                   将时间设置为中午

/pay         <家玩><金额>            server.pay                    向玩家转账

/ping        <玩家>                  server.ping.self               显⽰玩家的 ping
                                    server.ping.others

/rain        <世界>                  server.weather                 将天⽓改为下⾬

/repair                              server.repair                  修理你当前持有的物品 

/rename                             server.rename                   重命名您当前持有的物品

/r                                   server.reply                   快速回复上⼀位给你发消息的玩家

/restart                            server.restart                  重启 Minecraft 服务器 10 秒延迟

/rules                                                              显⽰服务器规则编辑：rules.yml  

/serversystem （<重新加载>）          serversystem.use                重新加载服务器系统的配置显⽰服务器系统的当前版本号 更新服务器系统（需要重新启动）
                (<版本>)             serversystem.reload 
（                <更新>）            serversystem.version
                                     serversystem.update

/sethome        <家>                  server.sethome.general          在当前位置设置家
                                      server.sethome.bypassmax
                                      server.sethome.<1 – 20>

/setspawn                             server.setspawn                 在当前位置设置 ServerSpawn

/setwarp      <Warp-Name>             server.warp                     设置坐标点

/sign         <内容>                  server.sign                      签署您当前持有的物品 

/skull        <玩家><玩家>             server.skull.self                给玩家⼀个玩家的头
                                      server.skull.others

/smelt                                server.smelt                    从你⽬前持有的矿⽯中熔化矿⽯，⽆需熔炉

/speed        <1 - 10>                server.speed.general            设置移动速度 默认值：1
              <⻜|⾛|玩家><步⾏|⻜>    server.speed.self
                                      server.speed.others

/stack                                server.stack                    将您当前持有的物品装满整个堆栈

/sudo         <玩家>                  server.sudo.use                 让您以其他玩家的⾝份发送聊天消息/命令
              <消息|命令>             server.sudo.exempt               

/suicide                              server.suicide                  导致你灭亡。

/sun                                  server.weather                  晴天

/tc           <消息>                  server.teamchat.send             向团队发送私⼈消息 接收来⾃团队的消息 
                                    server.teamchat.receive

/time         <Day|Noon|Night>        server.time                     改变世界时间

/tp           <玩家><玩家>            server.tp.self                    将玩家传送到玩家 2      
                                      server.tp.others
/tpa          <玩家>                  server.tpa                      发送传送请求：给玩家

/tpaccept                             server.tpaccept.general          接受传送请求
                                      server.tpaccept.bypassdelay

/tpahere      <玩家>                  server.tpahere                  根据要求将玩家传送给您

/tpo          <玩家><玩家>             server.tpo.self               将玩家传送到另⼀个（强制）
                                      server.tpo.others

/tpall        <玩家>                  server.tpall.self               将所有玩家传送到⼀名玩家
                                      server.tpall.others
                                      
/tpdeny                               server.tpdeny                   拒绝传送请求

/tphere       <玩家>                  server.tphere                   将玩家传送到你⾝边

/tpohere      <玩家>                  server.tpohere                  将玩家传送给你（强制）

/tppos        <玩家>                  server.tppos.self               将玩家传送到指定坐标
              <x><y><z><偏航><俯仰>   server.tppos.others

/tptoggle    （<玩家> 打开/关闭）      server.tptoggle.self             是否开启传送
                                    server.tptoggle.others   

/unban        <玩家>                  server.unban                      解禁玩家

/unmute       <玩家>                  server.unmute                     取消静⾳

/unsign                               erver.unsign                      删除您当前持有的项⽬的签名

/v                                    server.vanish.see                 对其他玩家隐藏⾃⼰
                                      server.vanish.self
                                      server.vanish.others

/warp       <Warp-Name>               server.warp.general               将你传送到经线
                                      server.warp.bypassdelay
                                      server.signs.warp
                                      server.signs.disposal
                                      server.signs.colorsigns

/wb         (<Player>)                server.workbench                    打开工作台

/weather     <sun|rain>               server.weather                    改变天⽓




                                     









                          



这是我刚刚翻译的
机器翻译 有些需要我手动调整 但我们这边已经很晚了 我太困了

**Comment by kroazi** [comment]
格式可能不对 因为我是用tab以及换行处理的格式 我也不会github 不然我可以把文档发给你

**Comment by TheBlackEntity** [comment]
这个问题是否仍然相关？

翻译：DeepL
