### ISSUE TITLE
Could not load 'plugins\ServerSystem.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by OcrSu** [TheBlackEntity/ServerSystem#16]
https://gist.github.com/OcrSu/8737e7653fab2ca8a4f592efba44c3b4

**Comment by TheBlackEntity** [comment]
Looks like a corrupt file to me.

Have you tried re-downloading the plugin?

**Comment by OcrSu** [comment]
Thank you for your prompt. I really haven't thought about it that way.

This file is indeed damaged. After I download it again, it will run normally.
