### ISSUE TITLE
xp tabbing

### ISSUE THREAD

**Issue by Grafhugo** [TheBlackEntity/ServerSystem#2]
bei /xp kommt <player> und nicht die eigentlichen spielernamen
![2021-12-05_14 22 53](https://user-images.githubusercontent.com/38762018/144748385-04ff7bf8-6efe-4dda-be47-5113dd0a7d8c.png)

**Comment by TheBlackEntity** [comment]
> bei /xp kommt und nicht die eigentlichen spielernamen ![2021-12-05_14 22 53](https://user-images.githubusercontent.com/38762018/144748385-04ff7bf8-6efe-4dda-be47-5113dd0a7d8c.png)

/xp ist kein Befehl von ServerSystem
