### ISSUE TITLE
[Translation Error] Ambiguous translation in Chinese

### ISSUE THREAD

**Issue by lightumcc** [TheBlackEntity/ServerSystem#8]
File: src/main/resources/messages_zhcn.yml line 143-145
Origin Text:
NoChat: "&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/_打开容器_&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (_打开容器_)!"
NoDrop: "&c&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/_打开容器_&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (_打开容器_)!"
NoInteract: "&c&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/_打开容器_&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (_打开容器_)!"

Correct Text:
NoChat: "&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/**与方块交互**&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (**与方块交互**)!"
NoDrop: "&c&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/**与方块交互**&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (**与方块交互**)!"
NoInteract: "&c&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/**与方块交互**&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (**与方块交互**)!"

**Comment by CCBlueX666** [comment]
btw after I manually change the translation file and restart my server, my changes always disappear, I think this may causes by some improper rules of replacing the translation files

**Comment by TheBlackEntity** [comment]
> File: src/main/resources/messages_zhcn.yml line 143-145
> Origin Text:
> NoChat: "&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/_打开容器_&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (_打开容器_)!"
> NoDrop: "&c&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/_打开容器_&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (_打开容器_)!"
> NoInteract: "&c&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/_打开容器_&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (_打开容器_)!"
> 
> Correct Text:
> NoChat: "&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/**与方块交互**&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (**与方块交互**)!"
> NoDrop: "&c&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/**与方块交互**&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (**与方块交互**)!"
> NoInteract: "&c&c隐身状态下无法进行下列操作 &4聊天/丢弃物品/拾取物品/**与方块交互**&c, 想要临时解除可以使用: &4/chat (聊天), /drop (丢弃物品), /pickup (拾取物品), /interact (**与方块交互**)!"

Hello,

Thank you for the correct translations.

I will forward it to my chinese translator just to make sure

**Comment by TheBlackEntity** [comment]
> btw after I manually change the translation file and restart my server, my changes always disappear, I think this may causes by some improper rules of replacing the translation files

Can you please send me the changed file before you reload ServerSystem oder restart your server?

**Comment by CCBlueX666** [comment]
https://drive.google.com/file/d/1NnH1voKSr8ianV9z8RrhW2Ff6-v11jYh/view?usp=sharing

**Comment by CCBlueX666** [comment]
after I reload/restart my server, the plugin rename my file into "messages.yml.backup-1656730436115" and the messages.yml become the messages_zhcn.yml

**Comment by TheBlackEntity** [comment]
Is this issue still relevant?

**Comment by lightumcc** [comment]
No, I fix it after change the config file
