### ISSUE TITLE
关于权限问题

### ISSUE THREAD

**Issue by kroazi** [TheBlackEntity/ServerSystem#9]
为何我没有找到如何配置权限的地方啊？导致我无op的账号任何一条指令都无法使用QAQ

**Comment by TheBlackEntity** [comment]
你可以在 "permissions.yml "文件中配置 ServerSystem 的权限。

ServerSystem 不是一个权限系统，所以你不能在那里给玩家分配权限。

(翻译：DeepL)

**Comment by kroazi** [comment]
感谢你的回复，我第一次开服对这些有些不懂，我了解到了像groupmanager这样的插件可以管理权限，你的插件很棒，我也希望能有官方的中文命令文档，非常感谢！

**Comment by TheBlackEntity** [comment]
我目前正在制作一部中国的纪录片。

不幸的是，我对 GroupManager 了解不多。
我总是使用 LuckPerms。




有一个 QQ 群，你可以从以中文为母语的人那里获得帮助。

如果你愿意，我可以看看如何进入。

我也在这个小组中。

我有时会在那里要求翻译


(翻译：DeepL)

**Comment by kroazi** [comment]
请问该qq群号是多少呢UwU

**Comment by TheBlackEntity** [comment]
906113923这是你需要的吗？
